### ISSUE TITLE
Application doesn't start

### ISSUE THREAD

**Issue by dotMR** [vonBrax/persons-app#1]
After installing deps (`npm install`) i've not been able to get the app to run

```
$ npm run server

> persons-app@0.0.0 server /Users/xxxxx/repo/persons-app
> cd server && node app.js

module.js:471
    throw err;
    ^

Error: Cannot find module 'cors'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/xxxx/repo/persons-app/server/app.js:6:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "server"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! persons-app@0.0.0 server: `cd server && node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the persons-app@0.0.0 server script 'cd server && node app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the persons-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd server && node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs persons-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls persons-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xxxxx/repo/persons-app/npm-debug.log
```

**Comment by vonBrax** [comment]
Hi Mario,

I'm really sorry for the inconvenience!

The error message says that the 'cors' module is not installed. Did you
remember to run 'npm install' on the /server directory too? I kept the
frontend and the backend projects separated since the focus of this
exercise was on the frontend application and I didn't want to put all the
dependencies together. Let me know if you did so then I can try to merge
both dependencies in a single package.json to see if that would work.
Alternatively, if just the 'cors' package is missing, you could try to
manually install it from npm by running 'npm i cors'.

Sorry again for the trouble!

Alexandre

2018-06-22 17:15 GMT+02:00 Mario Russo <notifications@github.com>:

**Comment by dotMR** [comment]
Hi Alexandre,

thanks! That worked for me. I can now run the app locally
